services:
  cesium:
    build: cesiumjs
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - network
    expose:
      - '8080'
    ports:
      - '8080:8080'

    volumes:
      - type: bind
        source: ${ROOT_DIR:?err}/gltf/cs
        target: /workspace/cs

  tileserv:
    build: tile_server
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - network
    expose:
      - '8081'
    ports:
      - '8081:8080'

    volumes:
      - type: bind
        source: ${ROOT_DIR:?err}/gltf/ts
        target: /workspace/ts

networks:
  network: {}
